site_name: 'python-12345'
site_description: 'Main documentation for the python-12345'
repo_url: https://github.com/ricardoandre97/python-12345
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'